### ISSUE TITLE
Namespace class loading error

### ISSUE THREAD

**Issue by michael-binder** [nitsan-technologies/ns_revolution_slider#1]
We have tested the extension and found that the namespace of the `ns_revolution_slider/Classes/Hooks/PageLayoutView.php` does not match the other namespaces. 
On Linux systems this results in an error message in the backend, which makes it not usable anymore
	
<img width="715" alt="Bildschirmfoto 2020-10-30 um 10 33 50" src="https://user-images.githubusercontent.com/21359926/97689110-6879d500-1a9b-11eb-8b65-5c28e745449e.png">

Since the namespace in the file is written in small letters
`namespace Nitsan\NsRevolutionSlider\Hooks;`

As soon as the namespace is adjusted, the backend works again on a Linux system.
`namespace NITSAN\NsRevolutionSlider\Hooks;`

Tested with:

- [NITSAN] Revolution Slider version 1.0.2
- TYPO3 9.5.22

**Comment by nitsan-technologies** [comment]
Hi @michael-binder 

Thanks for mentioning this issue.

We have adopted your mentioned point and released a [new version](https://github.com/nitsan-technologies/ns_revolution_slider/releases/tag/1.0.3). Please try the new version, and if still found any other things, please share your thought with us.

Thank you!
