### ISSUE TITLE
USer can't edit Slider-Records

### ISSUE THREAD

**Issue by izaquieltome** [nitsan-technologies/ns_revolution_slider#5]
I have a customer using the free version of the nitsan slider revolution. 
So for some days we experience a strange bahavior: 

all the Edit-Icons in List-Module are GONE. 
The Content Enditor can create new Slides - and new Sliders - but can't edit the ones which are alreay there.  (See Screenshot)

![List-·-Slides-·-Weingut-Christ-TYPO3-CMS-12-4-7-](https://github.com/nitsan-technologies/ns_revolution_slider/assets/41893913/400f79fc-d9bf-4be8-a372-b371a38a5b01)

We are working on Typo3 12.4.7, ns_revolution_slider 12 and PHP 8.2.12.

THe Content Editor has all rights he needs, Tables for Sliders and Slide Elements are enabled to show and edit. But nothing works.

Hopefully someone has an answer to this.

Thanks in advance,
Iza

**Comment by nitsan-technologies** [comment]
Hi @izaquieltome 

First of all, thank you very much for using our extension and sharing your valuable feedback. 

We checked this issue with the same environment. But we didn't face this. The editor's buttons are correctly visible and working.
https://i.imgur.com/3O8wTAg.png

It may be a permission-related issue, or can you please explain the test case for the same?

Cheers, Team @nilesh-nitsan
