### ISSUE TITLE
Media Library out of extension folder

### ISSUE THREAD

**Issue by jk-swe** [nitsan-technologies/ns_revolution_slider#6]
There has to be the possibility to move the media library auto of the extension folder.
Each deployment will leave an empty media library.

**Comment by nitsan-technologies** [comment]
Hey there,

Thank you for your valuable input.

We've advised setting the `fileadmin` directory to store Slider Revolution images. You can refer to https://docs.t3planet.com/en/latest/ExtNsRevolutionSlider/RevolutionSlider3.0/FAQ/Index.html for details.

If you encounter any problems during implementation, please don't hesitate to inform us at https://t3planet.com/support

Cheerts!

**Comment by jk-swe** [comment]
Thank you for your reply.
