### ISSUE TITLE
Missing Revolution Slider option in back-end

### ISSUE THREAD

**Issue by jaumepresaspuig** [nitsan-technologies/ns_revolution_slider#7]
Hello, I have just installed the free version 12.0.1 and in the back-end I can't see the Revolution Slider option:
![imatge](https://github.com/user-attachments/assets/728bb09e-39f2-465b-8a58-e6934a6d607e)
It's just missing, there is not either the NITSAN (or T3Planet as I see in your online demo) group. Is there something else that has to be done after the installation?

**Comment by nitsan-technologies** [comment]
Hey @jaumepresaspuig 

Thank you for reaching out!

To access the Revolution Slider’s custom backend module, you’ll need to purchase the premium version of the extension. You can buy it here:
[TYPO3 Slider Revolution Extension](https://t3planet.com/typo3-slider-revolution-extension)

For the free version, the backend module is not included. You can follow the installation guide in our documentation to ensure the extension is set up correctly:
[Free Version Installation Guide](https://docs.t3planet.com/en/latest/ExtNsRevolutionSlider/RevolutionSlider1.0/Installation/Index.html#for-free-version)

If you have any further questions or need assistance, feel free to let me know.

Cheers!

**Comment by jaumepresaspuig** [comment]
Thanks, it  makes sense, and it's fair. It just happens that in the documentation it's not clear that the backend module is not included in the free version.

**Comment by nitsan-technologies** [comment]
Hey @jaumepresaspuig 

Thank you for your feedback—it’s greatly appreciated!

You’re absolutely right; the documentation could be clearer about the backend module not being included in the free version. We’ll make sure to update it to avoid any confusion in the future.

If you have any other questions or need further clarification, feel free to reach out. We’re always here to help!

Cheers!
